#bloco de configuração da rede
network:
  #bloco de configuração do protocolo Ethernet
  ethernets:
    #configuração da Interface Física (Nome Lógico comando lshw)
    eth0:
      #desabilitando o suporte ao DHCP Client
      dhcp4: false
      #desativando o suporte ao IPv6
      #OBSERVAÇÃO IMPORTANTE: utilizar essa opção somente se você não está usando
      #na sua rede o recurso do IPv6
      link-local: []
      #alterar o endereço IPv4 para o seu cenário
      #OBSERVAÇÃO IMPORTANTE: configuração do Endereço IPv4 dentro de Colchetes
      addresses: [192.168.1.130/24]
      #alterar o gateway padrão para o seu cenário
      #OBSERVAÇÃO IMPORTANTE: a opção de Gateway4 foi descontinuada, recomendo
      #utilizar as opções de Routes do Netplan para configurar o Gateway padrão
      #gateway4: 172.16.1.254
      routes:
        #configuração da rota padrão (cuidado com o traço antes do to)
        - to: default
          #configuração do endereço IPv4 do Gateway
          via: 192.168.1.254
      #configuração dos servidores de DNS Preferencial e Alternativo
      nameservers:
        #alterar os servidores DNS para o seu cenário
        #OBSERVAÇÃO: configuração do Endereço IPv4 dentro de Colchetes e separados
        #por vírgula, recomendo pelo menos dois DNS Server serem configurados ou
        #somente o endereço do Servidor de DNS Local d Rede.
        addresses: [8.8.8.8, 8.8.4.4]
        #alterar a pesquisa de domínio para o seu cenário
        #OBSERVAÇÃO: configuração da pesquisa de Domínio dentro de Colchetes
        #search: [pti.intra]
  #fim do bloco de configuração do protocolo Ethernet versão 2
  version: 2